# Generated by Django 5.0.9 on 2026-02-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_appointment_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='checklist',
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='api.appointment')),
            ],
        ),
    ]
