# Generated by Django 5.0.9 on 2026-02-16 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_appointment_checklist_checklistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('user', 'appointment_date', 'appointment_time'), name='unique_user_appointment_slot'),
        ),
    ]
